name: pikaday_datepicker_angular2
description: Provides a datepicker as AngularDart3 component which wrapps the lightweight pikaday js-library.
version: 2.2.0
author: Stephan Schroeder <simon.void+github@gmail.com>
homepage: https://github.com/simon-void/pikaday_datepicker_angular2

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  angular: ^6.0.0

dev_dependencies:
  build_runner: ^1.7.0
  build_web_compilers: ^2.4.0