name: pikaday_datepicker_angular2
description: Provides a datepicker as AngularDart3 component which wrapps the lightweight pikaday js-library.
version: 2.2.0
author: Stephan Schroeder <simon.void+github@gmail.com>
homepage: https://github.com/simon-void/pikaday_datepicker_angular2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  angular: ^5.1.0

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^0.4.0